### ISSUE TITLE
Generate index.yaml in chronological order for packages having same version

### ISSUE THREAD

**Issue by hayderimran7** [kubernetes-helm/chartmuseum#114]
**Issue **
When chartmuseum generates index.yaml for charts of a specific package (lets say `mysql`), the order of each chart  with same semantic version are not chronological in order. Charts with same version for a specific package e.g. `mysql` should be in chronological order in index.yaml so that we get latest chart of same semantic version

**Description**

consider the following, the charts of `server` all have same Public semantic version i.e. `1.2.0-dev9464` however since they are uploaded via CI, we append the build number to local version (after `+` symbol) .  
Ideally we would want to retrieve the latest as the one that has highest local build version which means it is the one most recently uploaded, even though public semantic version is unchanged.  
So the `index.yaml` looks as following currently 
```
  server:
  - apiVersion: v1
    created: 2018-04-25T18:15:15Z
    description: server (all workers)
    digest: 19e3c6da5f2eb5fab74e1476ec2bf1461250461b0f5303f17e0f88f5bf7781cb
    name: server
    urls:
    - charts/server-1.2.0-dev9464+1.f2b69e3.tgz
    version: 1.2.0-dev9464+1.f2b69e3
  - apiVersion: v1
    created: 2018-04-26T16:09:41Z
    description:server (all workers)
    digest: 15953fbfb3d0c5a9f93b60e1d751842f328704eaeaa74a646245a9c2504eda4a
    name: server
    urls:
    - charts/server-1.2.0-dev9464+2.80f44a3.tgz
    version: 1.2.0-dev9464+2.80f44a3
  - apiVersion: v1
    created: 2018-04-18T17:11:34Z
    description: server (all workers)
    digest: 12fb3dfa897f7c48f5161373910e9c152e3f179a4dfb2acb1e8efd44058cf9f5
    name: server
    urls:
    - charts/server-1.2.0-dev1+127.fe52a50.tgz
    version: 1.2.0-dev1+127.fe52a50
```
when helm client stores that yaml as repository cache, it picks whatever the first package is in list as latest, so it shows `1.2.0-dev9464+1.f2b69e3` as latest. which is wrong, because `1.2.0-dev1+127.fe52a50.tgz` is one most recently uploaded (as seen from `created` field) . 

**Proposed fix**  
For charts of same semantic version , the order should be chronological so that helm client when reads the first package( thats most recently uploaded) as latest, which is correct behavior

**Comment by nullin** [comment]
`pkg/repo/index.go`'s `Regenerate()` invokes `SortEntries()` from https://github.com/kubernetes/helm/blob/84bb77f183a4b1ae4c688a766b1d8351a937e67a/pkg/repo/index.go#L141 which should sort the entries in `index.yaml` just like we'll want them, but that doesn't seem to be the case. In another example of the entries in `index.yaml` that ChartMuseum produced, the entries are in random order. e.g.

```
apiVersion: v1
entries:
  mysql:
  - apiVersion: v1
    created: 2018-04-05T19:43:32Z
    description: A Helm chart for Kubernetes
    digest: e85152ac6ae89f53341507ac8669db98dc083f797dc5fed8039f6f8bdc9f8dcd
    name: mysql
    urls:
    - charts/mysql-0.1.0.tgz
    version: 0.1.0
  task-server:
  - apiVersion: v1
    created: 2018-04-26T18:48:29Z
    description: Task server
    digest: 50093c6584c99c88c2e3b0080109bdbea4e357eddd7ff768ad49c97963699a28
    name: task-server
    urls:
    - charts/task-server-1.2.0-dev9464+3.d506f25.tgz
    version: 1.2.0-dev9464+3.d506f25
  - apiVersion: v1
    created: 2018-04-26T19:22:12Z
    description: Task server
    digest: 40711be87e6b08b1f4bf10115aa57835a43d7f5affe56e090b0c2bbe91e049dd
    name: task-server
    urls:
    - charts/task-server-1.2.0-dev9464+4.1bbb5b9.tgz
    version: 1.2.0-dev9464+4.1bbb5b9
  - apiVersion: v1
    created: 2018-04-26T16:09:41Z
    description: Task server
    digest: 15953fbfb3d0c5a9f93b60e1d751842f328704eaeaa74a646245a9c2504eda4a
    name: task-server
    urls:
    - charts/task-server-1.2.0-dev9464+2.80f44a3.tgz
    version: 1.2.0-dev9464+2.80f44a3
  - apiVersion: v1
    created: 2018-04-25T18:15:15Z
    description: Task server
    digest: 19e3c6da5f2eb5fab74e1476ec2bf1461250461b0f5303f17e0f88f5bf7781cb
    name: task-server
    urls:
    - charts/task-server-1.2.0-dev9464+1.f2b69e3.tgz
    version: 1.2.0-dev9464+1.f2b69e3
  - apiVersion: v1
    created: 2018-04-18T20:06:31Z
    description: Task server
    digest: 730e561e3c2969bb4bef8336bc79a5fb8a2304cd17f62ddd34f36f2ffb253d03
    name: task-server
    urls:
    - charts/task-server-1.2.0-dev1+128.9ebe986.tgz
    version: 1.2.0-dev1+128.9ebe986
  - apiVersion: v1
    created: 2018-04-18T16:53:52Z
    description: Task server
    digest: a84d08d03fcc786ed1b38344e37457952e5b5ebb16f81e21ec5895fde7e92cdc
    name: task-server
    urls:
    - charts/task-server-1.2.0-dev1+126.e017a3f.tgz
    version: 1.2.0-dev1+126.e017a3f
  - apiVersion: v1
    created: 2018-04-23T19:17:04Z
    description: Task server
    digest: 2f79e4fd07b8c66883f49759098a4cf91162de81ece3e3c05f38704d50010c2d
    name: task-server
    urls:
    - charts/task-server-1.2.0-dev1+134.5e2d64e.tgz
    version: 1.2.0-dev1+134.5e2d64e
```
