### ISSUE TITLE
Helm install return 'failed to download' error

### ISSUE THREAD

**Issue by rmfish** [kubernetes-helm/chartmuseum#129]
Hi,
This error has already perplexed me for a long time.

```
helm install daily/service-geo
Error: failed to download "daily/service-geo" (hint: running `helm repo update` may help)
```

Info:
```
uname -a
Linux daily02 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "daily" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈

helm search daily
NAME             	CHART VERSION               	APP VERSION	DESCRIPTION
daily/service-geo	master_180506004437_2c84e673	2.0        	A Helm chart for Kubernetes

helm install daily/service-geo
Error: failed to download "daily/service-geo" (hint: running `helm repo update` may help)
```

The index.yaml:  
```
apiVersion: v1
entries:
  service-geo:
  - apiVersion: v1
    appVersion: "2.0"
    created: "2018-05-11T08:51:27Z"
    description: A Helm chart for Kubernetes
    digest: 536745de7d53ef4d9a501ce71f1d87959d7e2aca306d0ccf952c6c281dbc56d9
    name: service-geo
    urls:
    - http://chart.daily.net/charts/service-geo-master_180506004437_2c84e673.tgz
    version: master_180506004437_2c84e673
  - apiVersion: v1
```

The url ` http://chart.daily.net/charts/service-geo-master_180506004437_2c84e673.tgz` is downloadable with curl.

The chartmuseum is run with docker, the docker compose file is:
```
version: '2'
services:
 chartmuseum:
  image: "chartmuseum/chartmuseum:latest"
  #volumes:
  ports:
   - "8080"
  container_name: "chartmuseum"
  environment:
   - SERVICE_NAME=chartmuseum
   - SERVICE_TAGS=ha,public
   - PORT=8080
   - DEBUG=1
   - STORAGE=alibaba
   - STORAGE_ALIBABA_BUCKET=bucket
   - STORAGE_ALIBABA_PREFIX=repos/chart/daily
   - STORAGE_ALIBABA_ENDPOINT=oss-cn-hangzhou.aliyuncs.com
   - ALIBABA_CLOUD_ACCESS_KEY_ID=key_id
   - ALIBABA_CLOUD_ACCESS_KEY_SECRET=key_secret
   - CHART_URL=http://chart.daily.net
```
