### ISSUE TITLE
Extra slash added to chart URL

### ISSUE THREAD

**Issue by eonicle** [kubernetes-helm/chartmuseum#136]
ChartMuseum version: 0.7.0
Helm version: 2.9.1

I recently upgraded from 0.3.1 to 0.7.0 (using AWS S3 backend, basic auth, no multitennancy, no redis cache) - basically just upgraded docker image version. After that all chart that have extended semver version (like 0.0.0-develop) started failing to download - ChartMuseum returned malformed URLs like https://domain.com//charts/sample.tgz (notice the double slash). Removing slash by hand works fine. We tried downgrading to 0.6.0 - all started working like a charm. I am not a Go specialist, but the cause of problem might be just here: https://github.com/kubernetes-helm/chartmuseum/blob/3c628ff54e57947d273b9ffe35d7432203881861/pkg/chartmuseum/server/multitenant/cache.go#L394
This looks like the place where extra slash is added.
Important notice - all "classic" versioned charts worked fine (like 2.0.0, 1.13.27 etc.)
Anyway, thanks for your awesome project! We are so glad to have it in our production, If you need some additional info or help by any means - I am more than happy to help.

**Comment by jdolitsky** [comment]
@eonicle thanks for the kind words and thanks for opening!

Unfortunately I was not able to reproduce this issue, using Helm 2.9.1 and ChartMuseum 0.7.0

My first though was that you might be using the `--chart-url` option, but even testing with that results in a OK-looking index.yaml:
```
chartmuseum --debug --port=8080 \
  --storage=local --storage-local-rootdir=$(pwd)/charts \
  --chart-url=https://domain.com/
```
```
apiVersion: v1
entries:
  mychart:
  - created: "2018-06-01T10:02:25.74676208-04:00"
    digest: f69c66148b5908087b03b60cc84ffc3df7e5ac4d5dd69c5f0b69ba34143b5bd0
    name: mychart
    urls:
    - https://domain.com/charts/mychart-0.1.0.tgz
    version: 0.1.0
  - created: "2018-06-01T10:05:47.597206592-04:00"
    digest: 036797175e8926cecb4300bf00b2373b90ba1d1cb77901d58e2530f5174c14bd
    name: mychart
    urls:
    - https://domain.com/charts/mychart-0.0.0-develop.tgz
    version: 0.0.0-develop
generated: "2018-06-01T10:08:03-04:00"
```

Could you share a little more about your setup? For example, is this running behind a proxy? Which options are you using (i.e. chart-url)? Is there possible some environment variable accidentally getting picked up by chartmuseum?

> ChartMuseum returned malformed URLs 

How are you determining this? Examining index.yaml manually, or via some Helm CLI command?
