### ISSUE TITLE
Ingress and tls errors while installing new chart

### ISSUE THREAD

**Issue by jonasdkhansen** [kubernetes-helm/chartmuseum#87]
I try to install the latest version of chartmuseum, but getting errors about the ingress.

Helm version: v2.8.1
Host: GCP
Kubernetes: v1.9.3-gke.0

Command:
`helm install --name chartmuseum -f custom.yaml incubator/chartmuseum`

Custom.yaml:
```
ingress:
  enabled: true

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'

  hosts:
    chartmuseum.my-domain.com:
      - /charts
      - /index.yaml

  tls:
    secretName: chartmuseum-my-domain-tls
    hosts:
      - chartmuseum.my-domain.com

```

error:
`Error: release chartmuseum failed: Ingress in version "v1beta1" cannot be handled as a Ingress: v1beta1.Ingress: Spec: v1beta1.IngressSpec: TLS: []v1beta1.IngressTLS: ReadArrayCB: expect [ or n, but found: {, parsing 621 ...}],"tls":{... at {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"nginx","kubernetes.io/tls-acme":"true","nginx.ingress.kubernetes.io/rewrite-target":"/"},"labels":{"app":"chartmuseum","chart":"chartmuseum-0.4.4","heritage":"Tiller","release":"chartmuseum"},"name":"chartmuseum-chartmuseum","namespace":"default"},"spec":{"rules":[{"host":"chartmuseum.my-domain.com","http":{"paths":[{"backend":{"serviceName":"chartmuseum-chartmuseum","servicePort":8080},"path":"/charts"},{"backend":{"serviceName":"chartmuseum-chartmuseum","servicePort":8080},"path":"/index.yaml"}]}}],"tls":{"hosts":["chartmuseum.my-domain.com"],"secretName":"chartmuseum-my-domain-tls"}}}`

**Comment by jonasdkhansen** [comment]
Found the problem, which was the secretName in tls, missing a - in front, so it should be:
```
  tls:
    - secretName: chartmuseum-gg-tools-tls
      hosts:
        - chartmuseum.gg-tools.dk
```
